-- Created by: Arena.ai Agent Mode (AI) - NightCity MTA:SA resource
-- ---------------------------------------------------------------------------------------------
-- client.lua - NightCity: an empty, rain-soaked futuristic megacity at midnight (no people, no vehicles, no animals).
--   * every model is allocated with engineRequestModel("object"): no vanilla model is replaced
--   * the city (models.lua / layout.lua, generated by source/build.py) is created in small batches on "nc:show"
--   * the river gets createWater, the sky / fog / rain / clock are fixed to a wet midnight, ambient birds and vanilla ambience are muted
--   * lamp / sign glow and steam are billboards drawn with dxDrawMaterialLine3D (sprites.lua)
--   * procedural ambience (rain, wind, city hum, steam, neon buzz, thunder with a lightning flash, tunnel drone)
--   * wet.fx: wet ground (darker asphalt, puddles, screen-space reflection of the lit city); post.fx: cinematic grade.  /ncfx
-- City frame (layout.lua): origin = centre of the city, x east, y north, z = street level.  The server sends the world anchor
-- with nc:show (default: 900 m above the map, nothing of the vanilla world can poke through).
-- ---------------------------------------------------------------------------------------------
local CFG = {
    MODEL_STEP = 8,                              -- models loaded per step
    OBJECT_STEP = 80,                            -- objects created per step
    STEP_MS = 50,
    ANCHOR = { x = 0.0, y = 0.0, z = 900.0 },    -- fallback only: the server sends the real anchor with nc:show
    TIME = { 12, 0 },                            -- default start: noon (overridden by atmo.lua at runtime)
    WEATHER = 0,                                 -- extra-sunny (we let atmo.lua drive fog/rain/sky directly)
    FOG = 1200,
    FAR = 4600,
    RAIN = 0.0,                                  -- manual rain override (used when /ncrain is set)
    SKY = { 80, 130, 200, 170, 190, 230 },       -- neutral placeholder; atmo.lua overrides every frame
    SPRITE_MAX = 400,                            -- billboards drawn per frame
    SPRITE_CELL = 64,
    SOUND = true,
    DRY_IN_TUNNEL = true,
}

local WET_TEXTURES = { "nc_asphalt", "nc_alley", "nc_road_ave", "nc_road_str", "nc_road_hwy", "nc_crosswalk", "nc_sidewalk", "nc_plaza", "nc_curb" }

local S = {
    loaded = false, loading = false, ids = {}, txd = {}, dffs = {}, cols = {},
    shown = false, zoff = 0, anchor = nil, objs = {}, water = {}, sounds = {}, timers = {},
    rain = CFG.RAIN, rainManual = false, hold = nil, tex = {}, grid = nil, steam = {}, drawn = 0, token = 0, waiters = {}, count = 0,
}
addEvent("nc:show", true)
addEvent("nc:hide", true)
addEvent("nc:zoff", true)

-- ---------------------------------------------------------------------------------------------
-- helpers
-- ---------------------------------------------------------------------------------------------
local function toWorld(px, py, pz)
    local A = S.anchor or CFG.ANCHOR
    return A.x + px, A.y + py, A.z + S.zoff + pz
end

local function toCity(wx, wy, wz)
    local A = S.anchor or CFG.ANCHOR
    return wx - A.x, wy - A.y, wz - A.z - S.zoff
end

local function track(t)
    if #S.timers > 96 then                       -- one-shot timers pile up: drop the dead ones
        local keep = {}
        for _, e in ipairs(S.timers) do if isTimer(e) then keep[#keep + 1] = e end end
        S.timers = keep
    end
    S.timers[#S.timers + 1] = t
    return t
end

local function dbg(msg) outputDebugString("[NightCity] " .. msg, 3) end
local function say(msg, r, g, b) outputChatBox("#52d8ff[NightCity] #ffffff" .. msg, r or 255, g or 255, b or 255, true) end
local function rnd(a, b) return a + (b - a) * math.random() end
local function clamp(v, a, b) if v < a then return a elseif v > b then return b end return v end

local function cityDist()
    local px, py = getElementPosition(localPlayer)
    local cx, cy = toWorld(0, 0, 0)
    return math.sqrt((px - cx) ^ 2 + (py - cy) ^ 2)
end

-- is a world position inside the covered part of the road tunnel (below street level, between the portals)?
local function inTunnel(wx, wy, wz)
    if not (S.shown and NC_TUNNEL) then return false end
    local px, py, pz = toCity(wx, wy, wz)
    local T = NC_TUNNEL
    return math.abs(px - T.x) < T.hw + 2 and py > T.cov0 and py < T.cov1 and pz < -1.0 and pz > T.zf - 3.0
end

-- ---------------------------------------------------------------------------------------------
-- models
-- ---------------------------------------------------------------------------------------------
local function loadOne(i)
    local def = NC_MODELS[i]
    local id = engineRequestModel("object")
    if not id then dbg("engineRequestModel failed for " .. def.name) return false end
    S.ids[i] = id
    local txd = S.txd[def.txd]
    if not txd then
        txd = engineLoadTXD("files/" .. def.txd .. ".txd")
        if not txd then dbg("cannot load TXD " .. def.txd) engineFreeModel(id) S.ids[i] = nil return false end
        S.txd[def.txd] = txd
    end
    local col = engineLoadCOL("files/" .. def.name .. ".col")
    local dff = engineLoadDFF("files/" .. def.name .. ".dff")
    if not col or not dff then
        dbg("cannot load " .. def.name)
        if col and isElement(col) then destroyElement(col) end
        if dff and isElement(dff) then destroyElement(dff) end
        engineFreeModel(id)
        S.ids[i] = nil
        return false
    end
    engineImportTXD(txd, id)
    engineReplaceCOL(col, id)
    engineReplaceModel(dff, id)
    pcall(engineSetModelLODDistance, id, def.dist or 300, true)      -- extended LOD: draw distances above 325 m
    S.cols[i], S.dffs[i] = col, dff
    return true
end

local freeModels

local function loadModels(done)
    if S.loaded then done(true) return end
    S.waiters[#S.waiters + 1] = done
    if S.loading then return end                 -- a load is already running: the callback is called when it finishes
    S.loading = true
    local i, n, failed = 0, #NC_MODELS, 0
    local function step()
        local stop = math.min(i + CFG.MODEL_STEP, n)
        while i < stop do
            i = i + 1
            if not loadOne(i) then failed = failed + 1 end
        end
        if i < n then
            setTimer(step, 50, 1)
        else
            S.loading = false
            S.loaded = failed == 0
            if failed > 0 then
                say(failed .. " of " .. n .. " models could not be loaded (see debugscript 3). The city is not created.", 255, 150, 120)
                freeModels()
            end
            local waiting = S.waiters
            S.waiters = {}
            for _, f in ipairs(waiting) do f(S.loaded) end
        end
    end
    step()
end

function freeModels()
    for _, id in pairs(S.ids) do engineFreeModel(id) end
    for _, e in pairs(S.dffs) do if isElement(e) then destroyElement(e) end end
    for _, e in pairs(S.cols) do if isElement(e) then destroyElement(e) end end
    for _, e in pairs(S.txd) do if isElement(e) then destroyElement(e) end end
    S.ids, S.dffs, S.cols, S.txd, S.loaded, S.loading = {}, {}, {}, {}, false, false
end

-- ---------------------------------------------------------------------------------------------
-- objects and water
-- ---------------------------------------------------------------------------------------------
local function spawnOne(o)
    local id = S.ids[o[1]]
    if not id then return nil end
    local x, y, z = toWorld(o[2], o[3], o[4])
    local ob = createObject(id, x, y, z, 0, 0, o[5])
    if not ob then return nil end
    setElementFrozen(ob, true)                   -- map geometry: never moved by physics
    if o[6] == "skyline" then setElementCollisionsEnabled(ob, false) end
    return ob
end

local function build(token, done)
    local i, n = 0, #NC_OBJECTS
    S.count = 0
    local function step()
        if not S.shown or S.token ~= token then return end           -- hidden (or shown again) while building: stop
        local stop = math.min(i + CFG.OBJECT_STEP, n)
        while i < stop do
            i = i + 1
            S.objs[i] = spawnOne(NC_OBJECTS[i])
            if S.objs[i] then S.count = S.count + 1 end
        end
        if i < n then
            track(setTimer(step, CFG.STEP_MS, 1))
        else
            done()
        end
    end
    step()
end

local function even(v) return math.floor(v / 2 + 0.5) * 2 end       -- GTA water polygons need even integer coordinates

local function createRiver()
    local made = 0
    for _, w in ipairs(NC_WATER) do
        local x0, y0, z = toWorld(w[1], w[2], w[5])
        local x1, y1 = toWorld(w[3], w[4], w[5])
        x0, y0, x1, y1 = even(x0), even(y0), even(x1), even(y1)
        local e = createWater(x0, y0, z, x1, y0, z, x0, y1, z, x1, y1, z)
        if e then S.water[#S.water + 1] = { e = e, z = w[5] } made = made + 1 end
    end
    if made == 0 then dbg("createWater failed") end
    pcall(setWaterColor, 8, 22, 34, 232)
    return made
end

-- ---------------------------------------------------------------------------------------------
-- atmosphere: wet midnight / clear noon / golden hour / fog ... driven by atmo.lua.
--   Default: sunny noon.  Override with /ncweather <name>, /nctime <h>, /ncpreset <name>,
--   /nccycle [on|off] [speed].  Rain is disabled by default (/ncrain 0); enable with
--   /ncweather rain|storm|drizzle|afterrain, or /ncrain <0..1> for a manual wetness slider.
-- ---------------------------------------------------------------------------------------------
local ATMO = { saved = nil, timer = nil, tunnel = false }

local function applySky()
    -- no-op placeholder: atmo.lua sets sky/sun/fog/rain each frame.
end

local function enforceAtmosphere()
    -- Tunnel dryness is handled inside atmo.lua; we keep a safety reset of heat-haze so
    -- GTA doesn't bleed weather states when switching presets fast.
    if ATMO.tunnel then pcall(setRainLevel, 0) end
end

local function applyAtmosphere()
    if not ATMO.saved then
        local okw, w = pcall(getWeather)
        local okt, h, m = pcall(getTime)
        ATMO.saved = { weather = okw and tonumber(w) or 0, h = okt and h or 12, m = okt and m or 0 }
    end
    pcall(setCloudsEnabled, true)                  -- atmo.lua toggles per weather
    pcall(setSunSize, 0)
    pcall(setBirdsEnabled, false)
    pcall(setAmbientSoundEnabled, "general", false)
    pcall(setAmbientSoundEnabled, "gunfire", false)
    pcall(setOcclusionsEnabled, false)
    pcall(setMinuteDuration, 2147483647)
    pcall(resetWaterColor)
    pcall(setWaterColor, 18, 30, 44, 230)
    enforceAtmosphere()
    pcall(NC_ATMO.setWeather, "sunny")            -- default start state
    pcall(NC_ATMO.setTime, 12, 0)
    if not (ATMO.timer and isTimer(ATMO.timer)) then
        ATMO.timer = setTimer(function() if S.shown then enforceAtmosphere() end end, 1000, 0)
    end
    if not ATMO.renderHook then
        ATMO.renderHook = function() NC_ATMO.tick(getTickCount()) end
        addEventHandler("onClientPreRender", root, ATMO.renderHook)
    end
end

local function restoreAtmosphere()
    if not ATMO.saved then return end
    if ATMO.timer and isTimer(ATMO.timer) then killTimer(ATMO.timer) end
    ATMO.timer = nil
    if ATMO.renderHook then removeEventHandler("onClientPreRender", root, ATMO.renderHook) ATMO.renderHook = nil end
    pcall(resetSkyGradient)
    pcall(resetFogDistance)
    pcall(resetFarClipDistance)
    pcall(resetHeatHaze)
    pcall(resetWindVelocity)
    pcall(resetRainLevel)
    pcall(resetSunSize)
    pcall(resetSunColor)
    pcall(resetWaterColor)
    pcall(setCloudsEnabled, true)
    pcall(setBirdsEnabled, true)
    pcall(setAmbientSoundEnabled, "general", true)
    pcall(setAmbientSoundEnabled, "gunfire", true)
    pcall(setOcclusionsEnabled, true)
    pcall(setMinuteDuration, 1000)
    if ATMO.saved then
        pcall(setWeather, ATMO.saved.weather)
        pcall(setTime, ATMO.saved.h, ATMO.saved.m)
    end
    ATMO.saved = nil
    ATMO.tunnel = false
end

-- ---------------------------------------------------------------------------------------------
-- sprites: glow of lamps / signs, steam (billboards)
-- ---------------------------------------------------------------------------------------------
local function buildSpriteGrid()
    local cell = CFG.SPRITE_CELL
    local grid = {}
    for k, s in ipairs(NC_SPRITES) do
        local key = (math.floor(s[1] / cell) + 512) * 1024 + (math.floor(s[2] / cell) + 512)
        local l = grid[key]
        if not l then l = {} grid[key] = l end
        l[#l + 1] = k
    end
    S.grid = grid
end

local function drawSprites()
    if not S.shown or not S.grid or not S.tex.glow then return end
    local cx, cy, cz = getCameraMatrix()
    local px, py, pz = toCity(cx, cy, cz)
    local cell = CFG.SPRITE_CELL
    local gx0, gy0 = math.floor(px / cell), math.floor(py / cell)
    local now = getTickCount() / 1000
    local n, maxn = 0, CFG.SPRITE_MAX
    for gx = gx0 - 2, gx0 + 2 do
        for gy = gy0 - 2, gy0 + 2 do
            local l = S.grid[(gx + 512) * 1024 + (gy + 512)]
            if l then
                for _, k in ipairs(l) do
                    local s = NC_SPRITES[k]
                    local dx, dy, dz = s[1] - px, s[2] - py, s[3] - pz
                    local d2 = dx * dx + dy * dy + dz * dz
                    local size = s[4]
                    local maxd = 55 + size * 22
                    if d2 < maxd * maxd and n < maxn then
                        local f = 1 - math.sqrt(d2) / maxd
                        local wx, wy, wz = toWorld(s[1], s[2], s[3])
                        if s[8] == 1 then
                            local flick = 0.92 + 0.08 * math.sin(now * 7 + k)
                            local a = clamp(f * 2.2, 0, 1) * 205 * flick
                            dxDrawMaterialLine3D(wx, wy, wz - size * 0.5, wx, wy, wz + size * 0.5, S.tex.glow, size,
                                tocolor(math.floor(s[5] * 255 + 0.5), math.floor(s[6] * 255 + 0.5), math.floor(s[7] * 255 + 0.5), math.floor(a + 0.5)), false, cx, cy, cz)
                        elseif S.tex.steam then
                            local rise = (now * 0.45 + k * 0.37) % 1.6
                            local a = clamp(f * 2.0, 0, 1) * 70 * (1 - rise / 1.6)
                            dxDrawMaterialLine3D(wx, wy, wz + rise - size * 0.5, wx, wy, wz + rise + size * 0.5, S.tex.steam, size * (0.8 + rise * 0.25),
                                tocolor(150, 140, 160, math.floor(a + 0.5)), false, cx, cy, cz)
                        end
                        n = n + 1
                    end
                end
            end
        end
    end
    S.drawn = n
end

local function startSprites()
    S.tex.glow = dxCreateTexture("files/fx/glow.png", "argb", true, "clamp")
    S.tex.steam = dxCreateTexture("files/fx/steam.png", "argb", true, "clamp")
    if not S.tex.glow then dbg("glow.png could not be loaded: no light glow") return end
    buildSpriteGrid()
    addEventHandler("onClientRender", root, drawSprites)
    S.spritesOn = true
end

local function stopSprites()
    if S.spritesOn then removeEventHandler("onClientRender", root, drawSprites) end
    S.spritesOn = false
    for k, t in pairs(S.tex) do if t and isElement(t) then destroyElement(t) end S.tex[k] = nil end
    S.grid = nil
end

-- ---------------------------------------------------------------------------------------------
-- ambience
-- ---------------------------------------------------------------------------------------------
local amb = {}

local function snd2(file, loop, vol)
    if not CFG.SOUND then return nil end
    local s = playSound("files/audio/" .. file .. ".wav", loop and true or false)
    if s then
        setSoundVolume(s, vol or 1)
        S.sounds[#S.sounds + 1] = s
    end
    return s
end

local function snd3(file, px, py, pz, loop, vol, minD, maxD)
    if not CFG.SOUND then return nil end
    local x, y, z = toWorld(px, py, pz)
    local s = playSound3D("files/audio/" .. file .. ".wav", x, y, z, loop and true or false)
    if s then
        setSoundVolume(s, vol or 1)
        setSoundMinDistance(s, minD or 4)
        setSoundMaxDistance(s, maxD or 40)
        S.sounds[#S.sounds + 1] = s
    end
    return s
end

local function setVol(s, v) if s and isElement(s) then setSoundVolume(s, v) end end

-- lightning flash + thunder is driven by atmo.lua (which sets NC_ATMO.lightning and calls NC_ATMO_SFX).
local function sndShort(file, loop, vol)
    -- short non-looped one-shot used by atmo.lua for thunder claps
    return snd2(file, false, vol or 0.5)
end

local function startAmbience()
    amb.rain = snd2("rain_loop", true, 0)
    amb.wind = snd2("wind_loop", true, 0)
    amb.hum = snd2("hum_loop", true, 0)
    amb.drips = {}
    local T = NC_TUNNEL
    if T then
        for k = 1, 4 do
            local y = T.cov0 + (T.cov1 - T.cov0) * (k - 0.5) / 4
            local s = snd3("drip_loop", T.x + ((k % 2 == 0) and 5 or -5), y, T.zf + 2.0, true, 0.5, 3, 28)
            if s then amb.drips[#amb.drips + 1] = s end
        end
    end
    amb.near = {}
    track(setTimer(function()
        if not S.shown then return end
        local px, py, pz = getElementPosition(localPlayer)
        local inside = inTunnel(px, py, pz) and CFG.DRY_IN_TUNNEL
        local d = cityDist()
        local far = clamp((900 - d) / 300, 0, 1)
        if inside ~= ATMO.tunnel then
            ATMO.tunnel = inside
            enforceAtmosphere()                  -- no rain inside the tunnel
        end
        local rainAmt = S.rain                                   -- manual /ncrain override if non-nil
        if NC_ATMO and NC_ATMO.lerped and not S.rainManual then rainAmt = NC_ATMO.lerped.rain end
        local windAmt = (NC_ATMO.lerped and (NC_ATMO.lerped.wind[1] + NC_ATMO.lerped.wind[2]) / 5.0) or 0.3
        setVol(amb.rain, (inside and 0.04 or 0.30 + 0.55 * rainAmt) * far)
        setVol(amb.wind, (inside and 0.05 or 0.10 + 0.18 * windAmt) * far)
        setVol(amb.hum, (inside and 0.50 or 0.20) * far * (0.7 + 0.3 * (1 - ((NC_ATMO.lerped and NC_ATMO.lerped.sunAlt) or 0))))
    end, 250, 0))
    -- nearby steam vents and buzzing signs: a few 3D loops that follow the player
    track(setTimer(function()
        if not S.shown then return end
        for k, e in pairs(amb.near) do
            if not isElement(e.s) then amb.near[k] = nil end
        end
        local px, py, pz = getElementPosition(localPlayer)
        local cx, cy, cz = toCity(px, py, pz)
        local want, nw = {}, 0
        for k, s in ipairs(NC_SPRITES) do
            local dx, dy = s[1] - cx, s[2] - cy
            if dx * dx + dy * dy < 900 and (s[8] == 2 or s[4] >= 2.4) and math.abs(s[3] - cz) < 40 then
                want[k] = s
                nw = nw + 1
                if nw > 40 then break end
            end
        end
        local count = 0
        for k, e in pairs(amb.near) do
            if not want[k] then
                if isElement(e.s) then destroyElement(e.s) end
                amb.near[k] = nil
            else
                count = count + 1
            end
        end
        for k, s in pairs(want) do
            if count >= 6 then break end
            if not amb.near[k] then
                local snd = snd3(s[8] == 2 and "steam_loop" or "buzz_loop", s[1], s[2], s[3], true, s[8] == 2 and 0.55 or 0.4, 3, 26)
                if snd then amb.near[k] = { s = snd } count = count + 1 end
            end
        end
    end, 1500, 0))
end

local function stopAmbience()
    for _, t in ipairs(S.timers) do if isTimer(t) then killTimer(t) end end
    S.timers = {}
    for _, s in ipairs(S.sounds) do if isElement(s) then destroyElement(s) end end
    S.sounds = {}
    amb = {}
end

-- ---------------------------------------------------------------------------------------------
-- shaders: wet ground (wet.fx) and the cinematic grade (post.fx).  /ncfx cycles 0 off, 1 grade, 2 grade + wet ground
-- ---------------------------------------------------------------------------------------------
local FX = { wet = nil, post = nil, src = nil, w = 0, h = 0, mode = 0, on = false, gain = 1.0 }

local function fxFrame()
    local now = getTickCount()
    if not FX.src or not isElement(FX.src) then return end
    dxUpdateScreenSource(FX.src)
    local t = (now % 100000) / 1000
    -- gWet and all weather-related shader values are driven by atmo.lua via the NC_ATMO_WET / NC_ATMO_POST globals.
    if FX.post and isElement(FX.post) then
        dxSetShaderValue(FX.post, "gTime", t)
        dxDrawImage(0, 0, FX.w, FX.h, FX.post)
    end
end

local function wetOff()
    if FX.wet then
        for _, n in ipairs(WET_TEXTURES) do engineRemoveShaderFromWorldTexture(FX.wet, n) end
        if isElement(FX.wet) then destroyElement(FX.wet) end
    end
    FX.wet = nil
    _G.NC_ATMO_WET = nil
end

local function wetOn()
    if FX.wet then return true end
    local sh, tech = dxCreateShader("wet.fx")
    if not sh then dbg("wet.fx: " .. tostring(tech)) return false end
    if tech == "fallback" then dbg("wet.fx: shader model 3 is not available, wet ground disabled") destroyElement(sh) return false end
    local ax, ay, az = toWorld(0, 0, 0)
    local T = NC_TUNNEL
    if T then dxSetShaderValue(sh, "gTun", ax + T.x, ay + T.cov0, ay + T.cov1, az - 1.0) end
    dxSetShaderValue(sh, "gScreen", FX.src)
    dxSetShaderValue(sh, "gPix", 1 / FX.w, 1 / FX.h)
    dxSetShaderValue(sh, "gWet", 0)
    dxSetShaderValue(sh, "gRainStr", 0)
    dxSetShaderValue(sh, "gSheen", 0)
    dxSetShaderValue(sh, "gSunAlt", 1)
    dxSetShaderValue(sh, "gSunDir", 0, 0.4, 1)
    for _, n in ipairs(WET_TEXTURES) do engineApplyShaderToWorldTexture(sh, n) end
    FX.wet = sh
    _G.NC_ATMO_WET = sh            -- atmo.lua drives wetness/sun/sheen per frame
    return true
end

local function postOff()
    if FX.post and isElement(FX.post) then destroyElement(FX.post) end
    FX.post = nil
    _G.NC_ATMO_POST = nil
end

local function postOn()
    if FX.post then return true end
    local sh, tech = dxCreateShader("post.fx")
    if not sh then dbg("post.fx: " .. tostring(tech)) return false end
    if tech == "fallback" then dbg("post.fx: shader model 3 is not available, grade disabled") destroyElement(sh) return false end
    dxSetShaderValue(sh, "ScreenTexture", FX.src)
    dxSetShaderValue(sh, "gPix", 1 / FX.w, 1 / FX.h)
    dxSetShaderValue(sh, "gGain", FX.gain)
    dxSetShaderValue(sh, "gTint", 1, 1, 1)
    dxSetShaderValue(sh, "gSunAlt", 1)
    dxSetShaderValue(sh, "gHaz", 0, 0, 0)
    dxSetShaderValue(sh, "gBloom", 0.45)
    dxSetShaderValue(sh, "gVignette", 0.6)
    dxSetShaderValue(sh, "gGrain", 0.014)
    dxSetShaderValue(sh, "gContrast", 1.0)
    FX.post = sh
    _G.NC_ATMO_POST = sh           -- atmo.lua drives grade per frame
    return true
end

local function fxStop()
    if FX.on then removeEventHandler("onClientHUDRender", root, fxFrame) end
    FX.on = false
    wetOff()
    postOff()
    if FX.src and isElement(FX.src) then destroyElement(FX.src) end
    FX.src = nil
    FX.mode = 0
end

local function fxSet(mode)
    if mode == 0 then fxStop() return 0 end
    if not FX.src then
        local sw, sh = guiGetScreenSize()
        FX.w, FX.h = sw, sh
        FX.src = dxCreateScreenSource(sw, sh)
        if not FX.src then return 0 end
    end
    local okPost = postOn()
    local okWet = false
    if mode >= 2 then okWet = wetOn() else wetOff() end
    if not okPost and not okWet then fxStop() return 0 end
    if not FX.on then addEventHandler("onClientHUDRender", root, fxFrame) FX.on = true end
    FX.mode = (okWet and 2) or 1
    return FX.mode
end

addCommandHandler("ncfx", function(_, arg)
    if not S.shown then say("the city is not shown (/ncshow).") return end
    local want = tonumber(arg)
    if want == nil then want = (FX.mode + 1) % 3 end
    want = clamp(math.floor(want), 0, 2)
    local got = fxSet(want)
    if got == want then
        say("graphics: " .. ({ [0] = "OFF (plain)", [1] = "cinematic grade", [2] = "cinematic grade + wet reflective ground" })[got] .. "   (/ncfx 0|1|2)")
    elseif want > 0 and got == 0 then
        say("this graphics setup could not compile the shaders - running without them.", 255, 150, 120)
    else
        say("the wet ground shader could not be compiled here, running with the grade only.", 255, 190, 120)
    end
end)

addCommandHandler("ncexposure", function(_, arg)
    local v = tonumber(arg)
    if not v then say("usage: /ncexposure <0.3 .. 4>   (now " .. string.format("%.2f", FX.gain) .. ", 1 = as designed; needs /ncfx 1 or 2)") return end
    FX.gain = clamp(v, 0.3, 4.0)
    if FX.post and isElement(FX.post) then dxSetShaderValue(FX.post, "gGain", FX.gain) end
    say("exposure " .. string.format("%.2f", FX.gain) .. (FX.post and "" or "   (the grade shader is off: /ncfx 1)"))
end)

-- ---------------------------------------------------------------------------------------------
-- show / hide
-- ---------------------------------------------------------------------------------------------
local clearCity

local function waitGround(token, x, y, z, tries, done)
    if not S.shown or S.token ~= token then return end
    local hit = processLineOfSight(x, y, z + 4.0, x, y, z - 8.0, true, false, false, true, false)
    if hit then done(true) return end
    if tries <= 0 then done(false) return end
    track(setTimer(function() waitGround(token, x, y, z, tries - 1, done) end, 300, 1))
end

-- teleport inside the city: the player is held until the collision around the destination is streamed in (the sky city is 900 m up)
local function safeTeleport(x, y, z)
    setElementPosition(localPlayer, x, y, z)
    setElementVelocity(localPlayer, 0, 0, 0)
    S.hold = true
    S.tp = (S.tp or 0) + 1
    local mine = S.tp
    setElementFrozen(localPlayer, true)
    waitGround(S.token, x, y, z, 40, function(found)
        if S.tp ~= mine then return end                                  -- a newer teleport took over
        if found then
            setElementFrozen(localPlayer, false)
            S.hold = nil
        else
            say("the ground collision is not available here yet - you stay frozen. /ncview again or /nchide.", 255, 150, 120)
        end
    end)
end

local function showCity(zoff, ax, ay, az)
    if S.shown then clearCity() end
    S.token = S.token + 1
    local token = S.token
    S.zoff = zoff or 0
    if ax and ay and az then S.anchor = { x = ax, y = ay, z = az } end
    local near = cityDist() < 600
    if near then setElementFrozen(localPlayer, true) S.hold = true end        -- hold the player in the air until the ground exists
    if not S.loaded then say("loading " .. #NC_MODELS .. " models and " .. #NC_OBJECTS .. " objects - this takes a few seconds ...") end
    loadModels(function(ok)
        if S.token ~= token then return end                                    -- hidden or shown again while the models were loading
        if not ok then
            if near then setElementFrozen(localPlayer, false) S.hold = nil end
            return
        end
        S.shown = true
        applyAtmosphere()
        build(token, function()
            createRiver()
            startSprites()
            startAmbience()
            fxSet(2)
            _G.NC_ATMO_SFX = sndShort        -- let atmo.lua fire one-shot thunder etc.
            local P = NC_POINTS.spawn
            local x, y, z = toWorld(P[1], P[2], P[3])
            if near then
                waitGround(token, x, y, z, 40, function(ok2)
                    if ok2 then
                        setElementFrozen(localPlayer, false)
                        S.hold = nil
                    else
                        say("the ground collision is not available yet - you stay frozen. /nchide returns you to the map.", 255, 150, 120)
                    end
                end)
            end
            say(S.count .. " objects.  /nchide removes it, /nctour tour, /ncfree cam, /ncview teleport, /ncfx graphics, /ncexposure, /ncweather, /ncpreset, /nctime, /nccycle, /ncinfo")
        end)
    end)
end

function clearCity()
    S.token = S.token + 1                        -- cancels a show that is still loading / building
    for _, e in pairs(S.objs) do if e and isElement(e) then destroyElement(e) end end
    for _, w in pairs(S.water) do if w and isElement(w.e) then destroyElement(w.e) end end
    S.objs, S.water = {}, {}
    fxStop()
    stopSprites()
    stopAmbience()
    restoreAtmosphere()
    if S.hold then setElementFrozen(localPlayer, false) S.hold = nil end
    S.shown = false
    if NC and NC.onHide then NC.onHide() end
end

addEventHandler("nc:show", resourceRoot, function(zoff, ax, ay, az) showCity(zoff, ax, ay, az) end)
addEventHandler("nc:hide", resourceRoot, function()
    local was = S.shown
    clearCity()
    if was then say("NightCity removed.") end
end)

-- /nczoff trims the height of the whole city
addEventHandler("nc:zoff", resourceRoot, function(dz)
    S.zoff = S.zoff + dz
    if not S.shown then return end
    for k, e in pairs(S.objs) do
        if e and isElement(e) then
            local o = NC_OBJECTS[k]
            local x, y, z = toWorld(o[2], o[3], o[4])
            setElementPosition(e, x, y, z)
        end
    end
    for _, w in pairs(S.water) do
        if w and isElement(w.e) then pcall(setWaterLevel, w.e, (S.anchor or CFG.ANCHOR).z + S.zoff + w.z) end
    end
end)

-- safety net for the sky city: anyone who somehow steps off the edge is brought back to the spawn point
setTimer(function()
    if not S.shown or S.hold or not S.anchor or S.anchor.z < 300 then return end
    local px, py, pz = getElementPosition(localPlayer)
    local cx, cy, cz = toWorld(0, 0, 0)
    local dx, dy = math.abs(px - cx), math.abs(py - cy)
    local E = NC_EXTENT
    local outside = dx > (E.x1 - E.x0) / 2 + 40 or dy > (E.y1 - E.y0) / 2 + 40
    if (pz < cz - 40 and dx < 900 and dy < 900) or (outside and dx < 1100 and dy < 1100 and pz < cz + 30) then
        local P = NC_POINTS.spawn
        local x, y, z = toWorld(P[1], P[2], P[3] + 1.0)
        safeTeleport(x, y, z)
    end
end, 1000, 0)

-- ---------------------------------------------------------------------------------------------
-- small commands
-- ---------------------------------------------------------------------------------------------
addCommandHandler("ncrain", function(_, arg)
    local v = tonumber(arg)
    if not v then
        local cur = S.rainManual and S.rain or (NC_ATMO.lerped and NC_ATMO.lerped.rain or 0)
        say("usage: /ncrain <0 .. 1>   (now " .. string.format("%.2f", cur) .. "; sets manual override, weather becomes \"custom wet\").  /ncweather to return to presets.")
        return
    end
    S.rain = clamp(v, 0, 1)
    S.rainManual = (v > 0.001)
    if S.shown then
        say("manual rain " .. string.format("%.2f", S.rain) .. (S.rainManual and " (overrides weather preset; use /ncweather to release)" or " (dry)"))
    end
end)

addCommandHandler("nctime", function(_, h, m)
    local hh = tonumber(h)
    if not hh then
        say("usage: /nctime <hour 0-23> [minute]   or preset: dawn sunrise morning noon afternoon golden sunset dusk night midnight.  Now " .. string.format("%02d:%02d", math.floor(NC_ATMO.timeH), math.floor((NC_ATMO.timeH % 1) * 60)))
        return
    end
    NC_ATMO.setTime(hh, tonumber(m) or 0)
    if S.shown then say("clock " .. string.format("%02d:%02d", math.floor(NC_ATMO.timeH), math.floor((NC_ATMO.timeH % 1) * 60))) end
end)

addCommandHandler("ncpreset", function(_, name)
    if not name then
        say("usage: /ncpreset <dawn|sunrise|morning|noon|afternoon|golden|sunset|dusk|night|midnight>")
        return
    end
    NC_ATMO.setPreset(name)
    S.rainManual = false
    if S.shown then say("preset " .. name .. " (" .. string.format("%02d:%02d", math.floor(NC_ATMO.timeH), math.floor((NC_ATMO.timeH % 1) * 60)) .. ")") end
end)

addCommandHandler("ncweather", function(_, name)
    if not name or not NC_ATMO.setWeather(name) then
        local names = NC_ATMO.weatherList()
        say("weather: " .. table.concat(names, " | ") .. "   (now " .. NC_ATMO.weather .. ")")
        return
    end
    S.rainManual = false
    if S.shown then say("weather " .. name) end
end)

addCommandHandler("nccycle", function(_, on, speed)
    if on == nil then
        say("usage: /nccycle <on|off> [speed-seconds-per-hour]   default 12. Currently " .. (NC_ATMO.cycle and "ON" or "OFF"))
        return
    end
    local enable = (on == "on" or on == "1" or on == "true")
    local sp = tonumber(speed)
    NC_ATMO.setCycle(enable, sp)
    say("day/night cycle " .. (enable and ("ON, " .. NC_ATMO.cycleSpeed .. " s/hour") or "OFF"))
end)

addCommandHandler("ncview", function(_, name)
    if not S.shown then say("the city is not shown (/ncshow).") return end
    local P = name and NC_POINTS[name]
    if not P then
        local names = {}
        for k in pairs(NC_POINTS) do names[#names + 1] = k end
        table.sort(names)
        say("usage: /ncview <" .. table.concat(names, " | ") .. ">")
        return
    end
    local x, y, z = toWorld(P[1], P[2], P[3] + 0.5)
    safeTeleport(x, y, z)
end)

addCommandHandler("ncinfo", function()
    local nobj = 0
    for _, e in pairs(S.objs) do if e and isElement(e) then nobj = nobj + 1 end end
    local px, py, pz = getElementPosition(localPlayer)
    local cx, cy, cz = toCity(px, py, pz)
    say(string.format("shown=%s  models=%d  objects=%d  water=%d  glow sprites drawn=%d  graphics=%d  tunnel=%s  you: x %.0f y %.0f z %.1f (city frame)",
        tostring(S.shown), #NC_MODELS, nobj, #S.water, S.drawn, FX.mode, tostring(inTunnel(px, py, pz)), cx, cy, cz))
end)

-- ---------------------------------------------------------------------------------------------
-- shared with tour.lua
-- ---------------------------------------------------------------------------------------------
NC = { toWorld = toWorld, toCity = toCity, say = say, track = track, clamp = clamp, isShown = function() return S.shown end,
       hold = function() return S.hold end, onHide = nil,
       inTunnel = inTunnel }

addEventHandler("onClientResourceStart", resourceRoot, function()
    triggerServerEvent("nc:request", resourceRoot)
end)

addEventHandler("onClientResourceStop", resourceRoot, function()
    clearCity()
    freeModels()
    for _, t in ipairs(S.timers) do if isTimer(t) then killTimer(t) end end
end)
