-- Created by: Arena.ai Agent Mode (AI) - Castle MTA:SA resource
-- ---------------------------------------------------------------------------------------------
-- client.lua - loads the castle DFF / TXD / COL files and replaces vanilla object models.
-- GTA SA shows only ONE atomic per object model, so the castle is split into 4 parts (3 solid + 1 transparent for
-- cobwebs / flames / orbs), each one its own model, all placed at the same origin by the server:
--   12853 sw_gas01 (Dillimore petrol station)  12859 sw_cont03  12860 sw_cont04  12861 sw_cont05 (loading-bay containers)
--   12854 sw_gas01int -> gate leaf            12855 sw_copshop (Dillimore police station) -> door leaf
-- All originals have exactly one instance on the map; they are hidden with removeWorldModel while the resource runs
-- and restored when it stops.  The ids live in ids.lua (generated by build.py - change ID_PARTS there and rebuild).
-- ---------------------------------------------------------------------------------------------
-- ids / files come from ids.lua (generated by build.py; shared script).
local TXD_FILE = "files/Castle.txd"
local GATE_DFF, GATE_COL = "files/CastleGate.dff", "files/CastleGate.col"
local DOOR_DFF, DOOR_COL = "files/CastleDoor.dff", "files/CastleDoor.col"
local LOD_DISTANCE = 900.0          -- the castle is huge: keep it drawn from far away

local loaded = {}                   -- elements kept so that they can be destroyed on stop
local hidden = {}                   -- world models that were removed
local replaced = {}                 -- model ids that were replaced

local function fail(msg)
    outputChatBox("[Castle] " .. msg, 255, 80, 80)
    outputDebugString("[Castle] " .. msg, 1)
end

local function replaceOne(id, dffFile, colFile, txd, alpha)
    local col = engineLoadCOL(colFile)
    if not col then return fail("could not load " .. colFile) end
    local dff = engineLoadDFF(dffFile)
    if not dff then return fail("could not load " .. dffFile) end
    loaded[#loaded + 1] = col
    loaded[#loaded + 1] = dff
    if not engineReplaceCOL(col, id) then return fail("engineReplaceCOL failed for " .. id) end
    if not engineImportTXD(txd, id) then return fail("engineImportTXD failed for " .. id) end
    if not engineReplaceModel(dff, id, alpha and true or false) then return fail("engineReplaceModel failed for " .. id) end
    engineSetModelLODDistance(id, LOD_DISTANCE)
    replaced[#replaced + 1] = id
    return true
end

addEventHandler("onClientResourceStart", resourceRoot, function()
    local txd = engineLoadTXD(TXD_FILE)
    if not txd then return fail("could not load " .. TXD_FILE) end
    loaded[#loaded + 1] = txd
    local all = {}
    for _, p in ipairs(CASTLE_IDS.parts) do all[#all + 1] = p.id end
    all[#all + 1] = CASTLE_IDS.gate
    all[#all + 1] = CASTLE_IDS.door
    -- hide the original map objects that use these ids (one instance each)
    for _, id in ipairs(all) do
        if removeWorldModel(id, 6000, 0, 0, 0) then hidden[#hidden + 1] = id end
    end
    local okAll = true
    for _, p in ipairs(CASTLE_IDS.parts) do
        if not replaceOne(p.id, p.dff, p.col, txd, p.alpha) then okAll = false end
    end
    if not replaceOne(CASTLE_IDS.gate, GATE_DFF, GATE_COL, txd, false) then okAll = false end
    if not replaceOne(CASTLE_IDS.door, DOOR_DFF, DOOR_COL, txd, false) then okAll = false end
    if okAll then
        outputChatBox("[Castle] models loaded. Type /showx to build the castle in front of you, /hidex to remove it.", 120, 220, 120)
    end
end)

addEventHandler("onClientResourceStop", resourceRoot, function()
    for _, id in ipairs(hidden) do restoreWorldModel(id, 6000, 0, 0, 0) end
    for _, id in ipairs(replaced) do
        engineRestoreModel(id)
        engineResetModelLODDistance(id)
    end
    for _, e in ipairs(loaded) do
        if isElement(e) then destroyElement(e) end
    end
end)
