-- Created by: Arena.ai Agent Mode (AI) - Castle MTA:SA resource
-- GENERATED by source/build.py from cs/interiors.py (doors) - do not edit by hand
-- fields: model (gate|door), hinge = castle-space position of the leaf pivot, rz = closed angle, open_rz = open angle (degrees)
CASTLE_DOORS = {
    { name = "gate_l", model = "gate", hinge = { -2.000, 0.600, 0.000 }, rz = 0.0, open_rz = 95.0 },
    { name = "gate_r", model = "gate", hinge = { 2.000, 0.600, 0.000 }, rz = 180.0, open_rz = 85.0 },
    { name = "w_ground", model = "door", hinge = { -8.600, 1.900, 0.000 }, rz = 90.0, open_rz = 185.0 },
    { name = "w_upper", model = "door", hinge = { -8.600, 4.100, 6.800 }, rz = 90.0, open_rz = 185.0 },
    { name = "e_ground", model = "door", hinge = { 8.600, 1.900, 0.000 }, rz = 90.0, open_rz = -5.0 },
    { name = "e_upper", model = "door", hinge = { 8.600, 4.100, 6.800 }, rz = 90.0, open_rz = -5.0 },
    { name = "keep_w", model = "door", hinge = { -5.700, 25.800, 2.000 }, rz = 0.0, open_rz = 95.0 },
    { name = "keep_e", model = "door", hinge = { 5.700, 25.800, 2.000 }, rz = 180.0, open_rz = 85.0 },
}
