-- Created by: Arena.ai Agent Mode (AI) - Castle MTA:SA resource
-- GENERATED by source/build.py - do not edit by hand (shared script)
CASTLE_IDS = {
    gate = 12854, door = 12855,
    -- the castle is split in parts, one atomic per object model; all parts are created at the same origin
    parts = {
        { id = 12853, dff = "files/Castle.dff", col = "files/Castle.col", alpha = false },
        { id = 12859, dff = "files/CastlePart2.dff", col = "files/CastlePart2.col", alpha = false },
        { id = 12860, dff = "files/CastlePart3.dff", col = "files/CastlePart3.col", alpha = false },
        { id = 12861, dff = "files/CastleFx.dff", col = "files/CastleFx.col", alpha = true },
    },
}
