-- Created by: Arena.ai Agent Mode (AI) - Castle MTA:SA resource
-- ---------------------------------------------------------------------------------------------
-- server.lua - /showx builds the castle in front of the player, /hidex removes it.
-- The two gate leaves, the six interior doors and the keep doors are separate objects that swing open
-- by themselves when a player comes close (moveObject rotation around the hinge) and close again.
-- Door table (hinge positions / angles in castle space) comes from doors_data.lua (generated by build.py).
-- ---------------------------------------------------------------------------------------------
local CFG = {
        FORWARD = 16.0,       -- distance from the player to the castle origin (centre of the entrance floor)
    Z_OFFSET = 0.5,       -- origin height above the player's feet position: plinth is buried half a metre
    ADMIN_ONLY = false,   -- true: only members of the Admin ACL group may use the commands
    OPEN_TIME = 900,      -- ms for a door to swing
    REACH_GATE = 6.5,     -- m: distance from the leaf centre that triggers the gate
    REACH_DOOR = 2.6,     -- m: interior doors
    TICK = 400,           -- ms between proximity checks
}
local LEAF = { gate = 2.0, door = 1.7 }
local MODEL_OF = { gate = CASTLE_IDS.gate, door = CASTLE_IDS.door }   -- ids.lua (shared)

local castle = nil        -- { objs = {parts}, doors = {}, timer, owner, dim, int }

local function rotz(x, y, deg)
    local r = math.rad(deg)
    local c, s = math.cos(r), math.sin(r)
    return c * x - s * y, s * x + c * y
end

local function allowed(player)
    if not CFG.ADMIN_ONLY then return true end
    local acc = getAccountName(getPlayerAccount(player))
    return isObjectInACLGroup("user." .. acc, aclGetGroup("Admin")) and true or false
end

local function doorTick()
    if not castle then return end
    local players = getElementsByType("player")
    for _, d in ipairs(castle.doors) do
        if isElement(d.obj) and not d.busy then
            local near = false
            for _, p in ipairs(players) do
                if not isPedDead(p) and getElementDimension(p) == castle.dim and getElementInterior(p) == castle.int then
                    local px, py, pz = getElementPosition(p)
                    local dx, dy, dz = px - d.cx, py - d.cy, pz - d.cz
                    if dx * dx + dy * dy + dz * dz < d.reach * d.reach then near = true break end
                end
            end
            if near and d.state == "closed" then
                d.busy = true
                local x, y, z = getElementPosition(d.obj)
                moveObject(d.obj, CFG.OPEN_TIME, x, y, z, 0, 0, d.delta, "InOutQuad")
                setTimer(function() if d then d.busy = false d.state = "open" end end, CFG.OPEN_TIME + 60, 1)
            elseif (not near) and d.state == "open" then
                d.busy = true
                local x, y, z = getElementPosition(d.obj)
                moveObject(d.obj, CFG.OPEN_TIME, x, y, z, 0, 0, -d.delta, "InOutQuad")
                setTimer(function() if d then d.busy = false d.state = "closed" end end, CFG.OPEN_TIME + 60, 1)
            end
        end
    end
end

function hideCastle()
    if not castle then return false end
    if isTimer(castle.timer) then killTimer(castle.timer) end
    for _, d in ipairs(castle.doors) do
        if isElement(d.obj) then destroyElement(d.obj) end
    end
    for _, o in ipairs(castle.objs) do
        if isElement(o) then destroyElement(o) end
    end
    castle = nil
    return true
end

function showCastle(player)
    hideCastle()
    local px, py, pz = getElementPosition(player)
    local _, _, yaw = getElementRotation(player)
    if isPedInVehicle(player) then
        local veh = getPedOccupiedVehicle(player)
        _, _, yaw = getElementRotation(veh)
    end
    -- local +y (the direction the castle extends in) = the direction the player is facing
    local fx, fy = rotz(0, CFG.FORWARD, yaw)
    local ox, oy, oz = px + fx, py + fy, pz + CFG.Z_OFFSET
    local dim, int = getElementDimension(player), getElementInterior(player)

    castle = { objs = {}, doors = {}, owner = player, dim = dim, int = int }
    -- the castle consists of several object models (one atomic each) at the very same position / rotation
    for _, p in ipairs(CASTLE_IDS.parts) do
        local obj = createObject(p.id, ox, oy, oz, 0, 0, yaw)
        if not obj then
            hideCastle()
            return false, "createObject failed (model " .. p.id .. ")"
        end
        setElementDimension(obj, dim)
        setElementInterior(obj, int)
        setObjectBreakable(obj, false)
        castle.objs[#castle.objs + 1] = obj
    end

    for _, d in ipairs(CASTLE_DOORS) do
        local hx, hy = rotz(d.hinge[1], d.hinge[2], yaw)
        local wx, wy, wz = ox + hx, oy + hy, oz + d.hinge[3]
        local closed = (yaw + d.rz) % 360
        local o = createObject(MODEL_OF[d.model], wx, wy, wz, 0, 0, closed)
        if o then
            setElementDimension(o, dim)
            setElementInterior(o, int)
            setObjectBreakable(o, false)
            -- leaf centre (for the proximity test): along the leaf direction, at half length and 1.2 m up
            local lx, ly = rotz(LEAF[d.model] * 0.5, 0, yaw + d.rz)
            castle.doors[#castle.doors + 1] = {
                obj = o, name = d.name, state = "closed", busy = false,
                cx = wx + lx, cy = wy + ly, cz = wz + 1.2,
                reach = (d.model == "gate") and CFG.REACH_GATE or CFG.REACH_DOOR,
                delta = d.open_rz - d.rz,
            }
        end
    end
    castle.timer = setTimer(doorTick, CFG.TICK, 0)
    return true, string.format("%.1f %.1f %.1f", ox, oy, oz)
end

addCommandHandler("showx", function(player)
    if not allowed(player) then return outputChatBox("[Castle] you are not allowed to use /showx", player, 255, 80, 80) end
    local ok, info = showCastle(player)
    if ok then
        outputChatBox("[Castle] the castle stands in front of you (origin " .. info .. "). Walk up the steps - the gate opens by itself.  /hidex removes it.", player, 120, 220, 120)
    else
        outputChatBox("[Castle] " .. tostring(info), player, 255, 80, 80)
    end
end)

addCommandHandler("hidex", function(player)
    if not allowed(player) then return outputChatBox("[Castle] you are not allowed to use /hidex", player, 255, 80, 80) end
    if hideCastle() then
        outputChatBox("[Castle] castle removed.", player, 120, 220, 120)
    else
        outputChatBox("[Castle] there is no castle to remove.", player, 255, 200, 80)
    end
end)

addEventHandler("onResourceStop", resourceRoot, function() hideCastle() end)
