// Stage 3: camera-only screen-space motion estimate. The game does not expose
// object motion vectors to a resource. This derives approximate camera flow from
// camera pose plus the depth texture generated by depth.fx; moving objects are
// rejected later with depth/luminance/reactive tests rather than being claimed
// to have true per-object vectors.
texture DepthTexture;
float2 TexelSize;
float FarPlane;
float UseDepth;
float4 CameraMotion;          // rotation-right, rotation-up, camera-translation-right/up
float CameraMotionForward;    // camera translation along the current view direction
float2 FocalScale;
float2 JitterDeltaUV;

sampler DepthSampler = sampler_state
{
    Texture = (DepthTexture);
    MinFilter = Point;
    MagFilter = Point;
    MipFilter = None;
    AddressU = Clamp;
    AddressV = Clamp;
};

float DecodeDepth24(float3 encoded)
{
    return encoded.r + encoded.g / 255.0 + encoded.b / 65025.0;
}

float4 MotionEstimatePS(float2 uv : TEXCOORD0) : COLOR0
{
    float depth = 80.0;
    if (UseDepth > 0.5)
    {
        float2 safeUV = clamp(uv, TexelSize * 0.5, 1.0 - TexelSize * 0.5);
        depth = max(DecodeDepth24(tex2D(DepthSampler, safeUV).rgb) * FarPlane, 2.0);
    }

    float fx = max(FocalScale.x, 0.05);
    float fy = max(FocalScale.y, 0.05);
    float2 velocity;
    velocity.x = (CameraMotion.x + CameraMotion.z / depth) * fx;
    velocity.y = (-CameraMotion.y - CameraMotion.w / depth) * fy;
    // Forward camera travel moves static-scene image features outward; the
    // previous-frame lookup therefore needs the opposite radial offset.
    velocity -= (uv - 0.5) * (CameraMotionForward / depth);
    velocity += JitterDeltaUV;

    // Two 8-bit channels encode +/- 0.125 UV/frame. Clipped or fast motion is
    // written into B as a reactive hint so temporal history is reduced.
    float2 clipped = clamp(velocity, -0.125, 0.125);
    float motionMagnitude = max(abs(velocity.x), abs(velocity.y));
    float reactive = saturate((motionMagnitude - 0.035) * 18.0);
    float2 encoded = clipped * 4.0 + 0.5;
    return float4(saturate(encoded), reactive, 1.0);
}

technique Main
{
    pass P0
    {
        ZEnable = FALSE;
        ZWriteEnable = FALSE;
        AlphaBlendEnable = FALSE;
        PixelShader = compile ps_2_0 MotionEstimatePS();
    }
}

technique Fallback
{
    pass P0
    {
        ZEnable = FALSE;
        ZWriteEnable = FALSE;
        Texture[0] = DepthTexture;
        ColorOp[0] = SelectArg1;
        ColorArg1[0] = Texture;
        AlphaOp[0] = SelectArg1;
        AlphaArg1[0] = Texture;
        ColorOp[1] = Disable;
        AlphaOp[1] = Disable;
    }
}
